version: '3.8'
services:
  arweave-node:
    container_name: arweave-node-build
    image: arweave-node:latest
    build:
      context: ./erlang_docker/
      dockerfile: ./Dockerfile-arweave-node
    ports:
      - "1984:1984"
    restart: always
    environment:
      # AR_RUNMODE: ${AR_RUNMODE?err} #set to <-r test> in .env for hashrate benchmarking 
        AR_RUNMODE: test
    volumes:
      - "../ardata:/mnt/arweave-data"
  # Postgres Configuration
  postgres:
    image: postgres:12
    volumes:
      - database:/var/lib/postgresql/data
      - app:/app
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: arweave
      POSTGRES_PASSWORD: arweave
      POSTGRES_DB: arweave
    command: -p 5432
  # Gateway Configuration
  server:
    build:
      context: ./gateway/
      dockerfile: ./docker/gateway.dockerfile
    volumes:
      - app:/app
    ports: 
      - 3000:3000
    environment:
      PORT: 3000
    
volumes:
  database:
  app:

