version: '3.8'
services:
  #arweave-node:
  #  container_name: arweave-node-build
  #  image: arweave-node:latest
  #  build:
  #    context: ./erlang_docker/
  #    dockerfile: ./Dockerfile-arweave-node
  #  ports:
  #    - "1984:1984"
  #  restart: always
  #  environment:
  #      AR_RUNMODE: test
  #  volumes:
  #    - "../ardata:/mnt/arweave-data"
  # Postgres Configuration
  postgres:
    image: postgres:12
    volumes:
      - database:/var/lib/postgresql/data
      - app:/app
    expose:
      - ${DATABASE_PORT}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    command: -p ${DATABASE_PORT}
  # Gateway Configuration
  gateway:
    build:
      context: ./gateway
      dockerfile: docker/gateway.dockerfile
    volumes:
      - app:/app
    links:
      - postgres
    ports: 
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
    
volumes:
  database:
  app:

